### ISSUE TITLE
Why require ext-ssh2?

### ISSUE THREAD

**Issue by darvanen** [mikemiles86/bazaarvoice-productfeed#1]
Why does this module require ext-ssh2 for PHP? There doesn't appear to be any usage of that extension in the code.
Is it possible to remove that dependency?

**Comment by balapalanisamy** [comment]
Is ssh2 extension required for this library?

**Comment by darvanen** [comment]
It was when I wrote the issue, I don't use it any more so I don't know.

**Comment by mikemiles86** [comment]
Resolved in PR #4
